export type HepExercise = {
  id: string;
  name: string;
  region: string;
  category: string;
  difficulty: "Easy" | "Moderate" | "Advanced";
  irritability: string[];
  equipment: string[];
  dosage: string;
  frequency: string;
  instructions: string[];
  cueing: string[];
  commonErrors: string[];
  regression: string[];
  progression: string[];
  patientText: string;
  tags?: string[];
  videoUrl?: string;
  imageUrl?: string;
};
